import collapsedLogo from "../../assets/image/collapsedLogo.png";

export const rowData = [
    {
        id: 1,
        brand: "칠성",
        name: "사이다",
        capacity: 500,
        price: 2000,
        date: new Date("2021-01-01"),
        image: collapsedLogo,
        button1: false,
        button2: false,
        button3: false,
    },
    {
        brand: "칠성",
        name: "사이다",
        capacity: 1000,
        price: 3000,
        date: new Date("2021-01-01"),
        image: "https://cdn4.buysellads.net/uu/1/127419/1670532337-Stock2.jpg",
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 2,
        brand: "칠성",
        name: "제로사이다",
        capacity: 360,
        price: 1000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 3,
        brand: "펩시",
        name: "콜라",
        capacity: 500,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 4,
        brand: "펩시",
        name: "제로콜라",
        capacity: 500,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 5,
        brand: "코카콜라",
        name: "콜라",
        capacity: 500,
        price: 1800,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 6,
        brand: "코카콜라",
        name: "제로콜라",
        capacity: 500,
        price: 2000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 7,
        brand: "해태",
        name: "갈아만든배",
        capacity: 360,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 8,
        brand: "칠성",
        name: "사이다",
        capacity: 500,
        price: 2000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 9,
        brand: "칠성",
        name: "사이다",
        capacity: 1000,
        price: 3000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 10,
        brand: "칠성",
        name: "제로사이다",
        capacity: 360,
        price: 1000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 11,
        brand: "펩시",
        name: "콜라",
        capacity: 500,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 12,
        brand: "펩시",
        name: "제로콜라",
        capacity: 500,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 13,
        brand: "코카콜라",
        name: "콜라",
        capacity: 500,
        price: 1800,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 14,
        brand: "코카콜라",
        name: "제로콜라",
        capacity: 500,
        price: 2000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 15,
        brand: "해태",
        name: "갈아만든배",
        capacity: 360,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 16,
        brand: "칠성",
        name: "사이다",
        capacity: 500,
        price: 2000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 17,
        brand: "칠성",
        name: "사이다",
        capacity: 1000,
        price: 3000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 18,
        brand: "칠성",
        name: "제로사이다",
        capacity: 360,
        price: 1000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 19,
        brand: "펩시",
        name: "콜라",
        capacity: 500,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 20,
        brand: "펩시",
        name: "제로콜라",
        capacity: 500,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 21,
        brand: "코카콜라",
        name: "콜라",
        capacity: 500,
        price: 1800,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 22,
        brand: "코카콜라",
        name: "제로콜라",
        capacity: 500,
        price: 2000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 23,
        brand: "해태",
        name: "갈아만든배",
        capacity: 360,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 24,
        brand: "칠성",
        name: "사이다",
        capacity: 500,
        price: 2000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 25,
        brand: "칠성",
        name: "사이다",
        capacity: 1000,
        price: 3000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 26,
        brand: "칠성",
        name: "제로사이다",
        capacity: 360,
        price: 1000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 27,
        brand: "펩시",
        name: "콜라",
        capacity: 500,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 28,
        brand: "펩시",
        name: "제로콜라",
        capacity: 500,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 29,
        brand: "코카콜라",
        name: "콜라",
        capacity: 500,
        price: 1800,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 30,
        brand: "코카콜라",
        name: "제로콜라",
        capacity: 500,
        price: 2000,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
    {
        id: 31,
        brand: "해태",
        name: "갈아만든배",
        capacity: 360,
        price: 1500,
        date: new Date("2021-01-01"),
        button1: false,
        button2: false,
        button3: false,
    },
];
