name: deploy

on:
    push:
        branches:
            - master
jobs:
    AUTO_DEPLOY:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Run scripts in server
              uses: appleboy/ssh-action@master
              with:
                  password: ${{ secrets.PASSWORD }}
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER_NAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.AWS_SSH_KEY }}
                  script: |
                      cd git/riaxo-developer-blog-frontend
                      git pull
                      yarn
                      yarn vite build
                      pm2 start yarn -- preview
